package main

import (
	"reflect"
	"testing"
)

func TestParseLinuxRouteLines(t *testing.T) {
	raw := `default via 192.168.1.1 dev eth0 proto dhcp metric 100
10.0.0.0/8 dev nezha-vpn scope link
172.19.0.0/30 dev nezha-vpn proto kernel scope link src 172.19.0.1
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.10 metric 100`

	got := parseLinuxRouteLines(raw)
	want := []linuxVPNTunRoute{
		{Prefix: "default", Dev: "eth0", Raw: "default via 192.168.1.1 dev eth0 proto dhcp metric 100"},
		{Prefix: "10.0.0.0/8", Dev: "nezha-vpn", Raw: "10.0.0.0/8 dev nezha-vpn scope link"},
		{Prefix: "172.19.0.0/30", Dev: "nezha-vpn", Raw: "172.19.0.0/30 dev nezha-vpn proto kernel scope link src 172.19.0.1"},
		{Prefix: "192.168.1.0/24", Dev: "eth0", Raw: "192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.10 metric 100"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("linux routes mismatch:\nwant %#v\ngot  %#v", want, got)
	}
}

func TestBuildLinuxRouteCleanupCommandsForTunInterface(t *testing.T) {
	before := `default via 192.168.1.1 dev eth0 proto dhcp metric 100
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.10 metric 100`
	after := `default dev nezha-vpn scope link
10.0.0.0/8 dev nezha-vpn scope link
default via 192.168.1.1 dev eth0 proto dhcp metric 100
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.10 metric 100`

	got := buildLinuxRouteCleanupCommands("nezha-vpn", before, after)
	want := []vpnTunCommand{
		{Name: "ip", Args: []string{"route", "del", "default", "dev", "nezha-vpn"}},
		{Name: "ip", Args: []string{"route", "del", "10.0.0.0/8", "dev", "nezha-vpn"}},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("linux route cleanup commands mismatch:\nwant %#v\ngot  %#v", want, got)
	}
}

func TestParseLinuxResolvConfDNSState(t *testing.T) {
	raw := `# generated by test
search lan
nameserver 192.168.1.1
nameserver 1.1.1.1
options edns0 trust-ad`

	got := parseLinuxResolvConfState("/etc/resolv.conf", raw)
	want := vpnTunDNSState{
		Path:    "/etc/resolv.conf",
		Raw:     raw,
		Servers: []string{"192.168.1.1", "1.1.1.1"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("linux resolv.conf state mismatch:\nwant %#v\ngot  %#v", want, got)
	}
}

func TestParseLinuxResolvedLinkDNSState(t *testing.T) {
	raw := `Global
         Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub

Link 2 (eth0)
    Current Scopes: DNS
         Protocols: +DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.1.1
       DNS Servers: 192.168.1.1 8.8.8.8
        DNS Domain: lan ~corp.example

Link 8 (nezha-vpn)
    Current Scopes: DNS
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 1.1.1.1
       DNS Servers: 1.1.1.1
        DNS Domain: ~.`

	got := parseLinuxResolvedLinkDNSState(raw)
	want := []vpnTunDNSState{
		{
			Source:    "systemd-resolved",
			Interface: "eth0",
			Servers:   []string{"192.168.1.1", "8.8.8.8"},
			Domains:   []string{"lan", "~corp.example"},
			Raw:       "default_route=true",
		},
		{
			Source:    "systemd-resolved",
			Interface: "nezha-vpn",
			Servers:   []string{"1.1.1.1"},
			Domains:   []string{"~."},
			Raw:       "default_route=false",
		},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("resolved link DNS state mismatch:\nwant %#v\ngot  %#v", want, got)
	}
}

func TestBuildLinuxResolvedDNSRestoreCommands(t *testing.T) {
	before := []vpnTunDNSState{
		{
			Source:    "systemd-resolved",
			Interface: "eth0",
			Servers:   []string{"192.168.1.1", "8.8.8.8"},
			Domains:   []string{"lan", "~corp.example"},
			Raw:       "default_route=true",
		},
	}
	afterRaw := `Link 2 (eth0)
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
       DNS Servers: 1.1.1.1
        DNS Domain: ~.

Link 8 (nezha-vpn)
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
       DNS Servers: 10.0.0.53
        DNS Domain: ~.`

	got := buildLinuxResolvedDNSRestoreCommands(before, afterRaw, "nezha-vpn")
	want := []vpnTunCommand{
		{Name: "resolvectl", Args: []string{"revert", "nezha-vpn"}},
		{Name: "resolvectl", Args: []string{"revert", "eth0"}},
		{Name: "resolvectl", Args: []string{"dns", "eth0", "192.168.1.1", "8.8.8.8"}},
		{Name: "resolvectl", Args: []string{"domain", "eth0", "lan", "~corp.example"}},
		{Name: "resolvectl", Args: []string{"default-route", "eth0", "yes"}},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("resolved DNS restore commands mismatch:\nwant %#v\ngot  %#v", want, got)
	}
}
